version: "0.1"
services:
  app:
    build: .
    ports:
      - "8443:8443" # code-server
      - "5000:5000" # Flask
      - "8080:8080" # http-server
      - "8787:8787" # RStudio
      - "8888:8888" # Jupyter
      - "8082:8082" # phpLiteAdmin
      - "5900:5900" # VNC server
      - "6081:6081" # VNC client
    volumes:
      - ./workspace:/workspace